apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo-app
  template:
    metadata:
      labels:
        app: flask-demo-app
    spec:
      containers:
      - name: flask-demo-app
        image: <ecr_repo_url>:latest
        ports:
        - containerPort: 8080

